#!/usr/bin/env bash


# Basic sanity check
old_dir="${HOME}/dotfiles.old"
if [ ! -d "${old_dir}" ]; then
  exit 1
fi

targets="`find . -maxdepth 1 -type f -name \".*\"`"

for target in $targets; do
    target_file="`basename $target`"
    unlink "${HOME}/$target_file"
done

cp ${old_dir}/* "${HOME}"
rm -rf "${old_dir}"

